---
name: Validate definitions

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint YAML files
        run: yamllint --format parsable --strict -c=tests/yamllint.yaml device-types/ module-types/
      - name: Run tests
        run: pytest --tb=short -v
